import { writeFileSync } from 'node:fs';
const ver = await (await fetch('http://127.0.0.1:9222/json/version')).json();
const ws = new WebSocket(ver.webSocketDebuggerUrl);
await new Promise((r,j)=>{ws.onopen=r;ws.onerror=j;});
let id=0; const p=new Map(); const lw=new Map();
ws.onmessage=e=>{const m=JSON.parse(e.data); if(m.id&&p.has(m.id)){const{res,rej}=p.get(m.id);p.delete(m.id);m.error?rej(new Error(JSON.stringify(m.error))):res(m.result);} else if(m.method==='Page.loadEventFired'&&lw.has(m.sessionId))lw.get(m.sessionId)();};
const send=(method,params={},sid)=>new Promise((res,rej)=>{const i=++id;p.set(i,{res,rej});ws.send(JSON.stringify(sid?{id:i,method,params,sessionId:sid}:{id:i,method,params}));});
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const {targetId}=await send('Target.createTarget',{url:'about:blank'});
const {sessionId}=await send('Target.attachToTarget',{targetId,flatten:true});
await send('Page.enable',{},sessionId);
await send('Network.enable',{},sessionId); await send('Network.setCacheDisabled',{cacheDisabled:true},sessionId);
await send('Emulation.setDeviceMetricsOverride',{width:1440,height:880,deviceScaleFactor:1,mobile:false},sessionId);
const loaded=new Promise(r=>lw.set(sessionId,r));
await send('Page.navigate',{url:'http://127.0.0.1:8000/index.html'},sessionId);
await Promise.race([loaded,sleep(8000)]); await sleep(1800);
const {data}=await send('Page.captureScreenshot',{format:'png',captureBeyondViewport:false},sessionId);
writeFileSync(process.argv[2],Buffer.from(data,'base64'));
await send('Target.closeTarget',{targetId}); ws.close(); console.log('OK');
